export NODE_PATH=/usr/local/lib/node_modules
export SVN_EDITOR=vim
source ~/git-completion.bash
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export PYTHONIOENCODING=utf-8
export PATH="$PATH:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools"
export ANDROID_HOME=/Users/sgalarneau/Library/Android/sdk
export PATH=$PATH:/usr/local/sbin
