import = [ "~/.config/alacritty/night_owl.toml" ]

live_config_reload = true

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[scrolling]
history = 5000
multiplier = 3

[window]
decorations = "none"
opacity = 1

[window.padding]
x = 2
y = 8
