import = [ "~/.config/alacritty/monokai_pro.toml" ]

live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[scrolling]
history = 5000
multiplier = 3

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 2
y = 8
